### ISSUE TITLE
Example code fails with PHP Fatal Error: Call to undefined method

### ISSUE THREAD

**Issue by skome** [OCLC-Developer-Network/oclc-auth-php#2]
Caveat: PHP is unfamiliar to me.  

I followed the installation instructions including to create the sample code file with our OCLC credentials.
When I run php mystest.php, it fails with the message: PHP Fatal error:  Call to undefined method Guzzle\Http\Client::getClient()

Does this mean that getClient() is not in my version of Guzzle\Http\Client?

**Comment by librarywebchic** [comment]
I've update the sample to include the line

require_once('vendor/autoload.php');

This is necessary to get the libraries to load.
